/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.*;

import static org.example.AppDebug.SET;

public class App {

    public static final int N = 3;
    public static final int W = 2;
    public static final int R = 2;
    public static final int T = 999;

    public static final int START = 5;
    public static final int T_END=T+1;
    public static final int C = 2;

    public static void main(String[] args) throws FileNotFoundException {

        AppDebug d = new AppDebug("set_test");
        AppDebug.ErrorDebug e = d.setFixedTest();
        System.out.println(e.error);

    }
}
