/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import akka.actor.ActorRef;
import org.example.msg.Debug;

import java.io.FileNotFoundException;

public class App {

    public static final int N = 3;
    public static final int W = 2;
    public static final int R = 2;
    public static final int T = 500;
    public static final int MSG_MAX_DELAY = 100;

    public static final int STARTING_NODES = 5;
    public static final int ROUNDS = 10;

    public static void main(String[] args) throws FileNotFoundException {

        AppDebug d = new AppDebug("coordinator_test");

        // d.coordinator.tell(new Debug.StartRoundMsg(), ActorRef.noSender());

        // test about set operations in a fixed network

        // d.setFixedTest();
        // String e = d.check_set_file();
        // System.out.println(e);

        // test about set and get operations (seq consistency check) in a fixed network

        // d.sequentialConsistencyTest();
        // String e = d.check_consistency_file();
        // System.out.println(e);

        // test about set in a dynamic network (join and leave operations)
        
        d.setDynamicTest();
        String e = d.check_dynamic_set_file();
        System.out.println(e);

    }
}
