/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import org.example.msg.*;

import akka.actor.ActorRef;
import akka.actor.ActorSystem;

public class App {
    public static final int N = 3;
    public static final int W = 2;
    public static final int R = 2;
    public static final int T = 9999;

    public static final int START = 5;

    public static void main(String[] args) {
        Random rng = new Random();

        ActorSystem system = ActorSystem.create("MarsSystem");

        ActorRef client1 = system.actorOf(Client.props("Alice"));
        ActorRef client2 = system.actorOf(Client.props("Bob"));

        List<ActorRef> nodes = new ArrayList<>();
        for (int i=0; i<START; i++) {
            nodes.add(system.actorOf(Node.props((i+1)*10)));
        }
        for (int i=0; i<START; i++) {
            ActorRef n = nodes.get(i);
            for (ActorRef node: nodes) {
                node.tell(new Node.DebugAddNodeMsg(n, (i+1)*10), n);
            }
        }

        // Set value
        nodes.get(rng.nextInt(nodes.size())).tell(new Set.InitiateMsg(5, "Mela"), client1);
        try { Thread.sleep(1000); } catch (InterruptedException e) {e.printStackTrace(); }
        // Update value
        nodes.get(rng.nextInt(nodes.size())).tell(new Set.InitiateMsg(5, "Banana"), client1);
        try { Thread.sleep(1000); } catch (InterruptedException e) {e.printStackTrace(); }
        // Read value
        nodes.get(rng.nextInt(nodes.size())).tell(new Get.InitiateMsg(5), client2);
        try { Thread.sleep(1000); } catch (InterruptedException e) {e.printStackTrace(); }

        // Join
        ActorRef newNode = system.actorOf(Node.props(25));
        ActorRef bootstrapping_peer = nodes.get(rng.nextInt(nodes.size()));
        bootstrapping_peer.tell(new Join.InitiateMsg(), newNode);

        nodes.add(newNode);

        try {
            System.out.println(">> Press Enter to End <<");
            System.in.read();
        }catch (Exception e) {}
        system.terminate();
    }
}
